# Generated by Django 2.1.2 on 2018-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComptTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_se', models.CharField(max_length=255, null=True)),
                ('compt_time', models.CharField(max_length=8, null=True)),
                ('frst_regist_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_regist_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_no', models.CharField(max_length=8, unique=True)),
                ('stage_ty_code', models.CharField(max_length=30, null=True)),
                ('boss_at', models.CharField(max_length=1, null=True)),
                ('gnrl_lmtt_time', models.CharField(max_length=8, null=True)),
                ('crown_lmtt_time', models.CharField(max_length=8, null=True)),
                ('frst_regist_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_regist_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageComptTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_no', models.SmallIntegerField(unique=True)),
                ('compt_time', models.SmallIntegerField(null=True)),
                ('compt_se', models.CharField(default='normal', max_length=255, null=True)),
                ('frst_regist_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_regist_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
