# Generated by Django 2.1.2 on 2018-10-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComptTime',
        ),
    ]
