# Generated by Django 2.1.2 on 2018-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_delete_compttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_se', models.CharField(max_length=255, null=True)),
                ('compt_time', models.CharField(max_length=8, null=True)),
                ('frst_regist_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_regist_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
