# Generated by Django 2.1.2 on 2018-10-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_auto_20181022_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='compttime',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='memo.Stage'),
        ),
    ]
